"""add_sejarah_gambar

Revision ID: 018b7b14a875
Revises: 5931e5b2d5d2
Create Date: 2026-02-18 23:21:37.427011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018b7b14a875'
down_revision = '5931e5b2d5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengaturan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sejarah_gambar', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengaturan', schema=None) as batch_op:
        batch_op.drop_column('sejarah_gambar')

    # ### end Alembic commands ###
