"""Add_user_agent_to_ActivityLog

Revision ID: 162b3c3802ed
Revises: a82ea5f94fbf
Create Date: 2026-02-20 02:31:30.435862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162b3c3802ed'
down_revision = 'a82ea5f94fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    if 'activity_log' not in inspector.get_table_names():
        op.create_table('activity_log',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.id')),
            sa.Column('action', sa.String(length=50), nullable=False),
            sa.Column('target', sa.String(length=50), nullable=True),
            sa.Column('details', sa.Text(), nullable=True),
            sa.Column('ip_address', sa.String(length=45), nullable=True),
            sa.Column('user_agent', sa.String(length=255), nullable=True),
            sa.Column('timestamp', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    else:
        with op.batch_alter_table('activity_log', schema=None) as batch_op:
            batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'activity_log' in inspector.get_table_names():
        # Check if we should drop the table or just the column
        # Ideally we should reverse exactly what we did.
        # But determining if we created the table or just the column is hard without state.
        # Safe fallback: try to drop column. If it was a create table, we leave it (it's fine).
        # OR we could just drop column 'user_agent'
        try:
            with op.batch_alter_table('activity_log', schema=None) as batch_op:
                batch_op.drop_column('user_agent')
        except:
            pass
    # ### end Alembic commands ###
