"""Add_user_agent_to_ActivityLog

Revision ID: 162b3c3802ed
Revises: a82ea5f94fbf
Create Date: 2026-02-20 02:31:30.435862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162b3c3802ed'
down_revision = 'a82ea5f94fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
