"""Initial migration

Revision ID: 306207f774ab
Revises: 
Create Date: 2026-02-12 12:43:40.917331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306207f774ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kegiatan', sa.String(length=255), nullable=False),
    sa.Column('tanggal_mulai', sa.DateTime(), nullable=False),
    sa.Column('tanggal_selesai', sa.DateTime(), nullable=True),
    sa.Column('lokasi', sa.String(length=255), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('berita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('konten', sa.Text(), nullable=False),
    sa.Column('gambar', sa.String(length=255), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('penulis', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('galeri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=True),
    sa.Column('gambar', sa.String(length=255), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('galeri')
    op.drop_table('berita')
    op.drop_table('agenda')
    # ### end Alembic commands ###
