"""Add_indexes

Revision ID: 5931e5b2d5d2
Revises: d54d66b0d450
Create Date: 2026-02-18 21:21:41.601749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5931e5b2d5d2'
down_revision = 'd54d66b0d450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('berita', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_berita_kategori'), ['kategori'], unique=False)
        batch_op.create_index(batch_op.f('ix_berita_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('berita', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_berita_status'))
        batch_op.drop_index(batch_op.f('ix_berita_kategori'))

    # ### end Alembic commands ###
