"""create_missing_tables_program_pimpinan

Revision ID: 906d1ad451c9
Revises: 162b3c3802ed
Create Date: 2026-02-23 05:42:12.568684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906d1ad451c9'
down_revision = '162b3c3802ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pimpinan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('jabatan', sa.String(length=100), nullable=True),
    sa.Column('gambar', sa.String(length=255), nullable=True),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('gambar', sa.String(length=255), nullable=True),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pengaturan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiktok', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('maps_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sejarah', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('visi', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('misi', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')

    with op.batch_alter_table('pengaturan', schema=None) as batch_op:
        batch_op.drop_column('misi')
        batch_op.drop_column('visi')
        batch_op.drop_column('sejarah')
        batch_op.drop_column('maps_link')
        batch_op.drop_column('tiktok')

    op.drop_table('program')
    op.drop_table('pimpinan')
    # ### end Alembic commands ###
