"""add_hero_fields

Revision ID: a3472c80d3c7
Revises: 018b7b14a875
Create Date: 2026-02-19 00:20:17.427037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3472c80d3c7'
down_revision = '018b7b14a875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengaturan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_title_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hero_title_2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hero_title_3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hero_subtitle', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengaturan', schema=None) as batch_op:
        batch_op.drop_column('hero_subtitle')
        batch_op.drop_column('hero_title_3')
        batch_op.drop_column('hero_title_2')
        batch_op.drop_column('hero_title_1')

    # ### end Alembic commands ###
