"""add_statistics_fields

Revision ID: a82ea5f94fbf
Revises: b276e90a89b4
Create Date: 2026-02-19 23:16:44.853128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82ea5f94fbf'
down_revision = 'b276e90a89b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengaturan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah_santri', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jumlah_alumni', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jumlah_ustadz', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jumlah_kitab', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengaturan', schema=None) as batch_op:
        batch_op.drop_column('jumlah_kitab')
        batch_op.drop_column('jumlah_ustadz')
        batch_op.drop_column('jumlah_alumni')
        batch_op.drop_column('jumlah_santri')

    # ### end Alembic commands ###
