"""add_struktur_organisasi

Revision ID: b276e90a89b4
Revises: a3472c80d3c7
Create Date: 2026-02-19 23:08:45.970651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b276e90a89b4'
down_revision = 'a3472c80d3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengaturan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('struktur_organisasi_gambar', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengaturan', schema=None) as batch_op:
        batch_op.drop_column('struktur_organisasi_gambar')

    # ### end Alembic commands ###
