"""Update models with settings and details

Revision ID: d54d66b0d450
Revises: 0e1640dd6083
Create Date: 2026-02-12 13:31:33.244173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54d66b0d450'
down_revision = '0e1640dd6083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengaturan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_pesantren', sa.String(length=100), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('deskripsi_singkat', sa.Text(), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('youtube', sa.String(length=255), nullable=True),
    sa.Column('maps_embed', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('berita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('kategori', sa.String(length=50), nullable=True))

    with op.batch_alter_table('galeri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deskripsi', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galeri', schema=None) as batch_op:
        batch_op.drop_column('deskripsi')

    with op.batch_alter_table('berita', schema=None) as batch_op:
        batch_op.drop_column('kategori')
        batch_op.drop_column('status')

    op.drop_table('pengaturan')
    # ### end Alembic commands ###
