"""empty message

Revision ID: 440fec423034
Revises: cd87817e734a
Create Date: 2026-02-22 23:37:40.404372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440fec423034'
down_revision = 'cd87817e734a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mata_pelajaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kelompok', sa.String(length=50), nullable=True))

    with op.batch_alter_table('raport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sikap_akhlak', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sikap_kerajinan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sikap_kedisiplinan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sikap_kebersihan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('deskripsi_moral', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deskripsi_kognitif', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deskripsi_sosial', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deskripsi_bahasa', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deskripsi_seni', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deskripsi_diri', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raport', schema=None) as batch_op:
        batch_op.drop_column('deskripsi_diri')
        batch_op.drop_column('deskripsi_seni')
        batch_op.drop_column('deskripsi_bahasa')
        batch_op.drop_column('deskripsi_sosial')
        batch_op.drop_column('deskripsi_kognitif')
        batch_op.drop_column('deskripsi_moral')
        batch_op.drop_column('sikap_kebersihan')
        batch_op.drop_column('sikap_kedisiplinan')
        batch_op.drop_column('sikap_kerajinan')
        batch_op.drop_column('sikap_akhlak')

    with op.batch_alter_table('mata_pelajaran', schema=None) as batch_op:
        batch_op.drop_column('kelompok')

    # ### end Alembic commands ###
