"""update_schema

Revision ID: 69e25d86bd1f
Revises: 9d845167c853
Create Date: 2026-02-23 01:19:59.165840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e25d86bd1f'
down_revision = '9d845167c853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nilai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deskripsi', sa.String(length=255), nullable=True))

    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anak_ke', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jumlah_saudara', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('no_hp_wali', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.drop_column('no_hp_wali')
        batch_op.drop_column('jumlah_saudara')
        batch_op.drop_column('anak_ke')

    with op.batch_alter_table('nilai', schema=None) as batch_op:
        batch_op.drop_column('deskripsi')

    # ### end Alembic commands ###
