"""empty message

Revision ID: 764818cd2acd
Revises: e3b35158c5e8
Create Date: 2026-02-21 23:42:25.249089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764818cd2acd'
down_revision = 'e3b35158c5e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('konfigurasi_laporan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lembaga', sa.String(length=100), nullable=True),
    sa.Column('alamat_lembaga', sa.Text(), nullable=True),
    sa.Column('telepon_lembaga', sa.String(length=50), nullable=True),
    sa.Column('email_lembaga', sa.String(length=100), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('kota_ttd', sa.String(length=50), nullable=True),
    sa.Column('nama_ttd', sa.String(length=100), nullable=True),
    sa.Column('jabatan_ttd', sa.String(length=100), nullable=True),
    sa.Column('nip_ttd', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('konfigurasi_laporan')
    # ### end Alembic commands ###
