"""Initial migration

Revision ID: 7cbc6caa438a
Revises: 
Create Date: 2026-02-12 11:31:24.983601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbc6caa438a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mata_pelajaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_mapel', sa.String(length=100), nullable=False),
    sa.Column('jenjang', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('pengajar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('no_hp', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kelas', sa.String(length=50), nullable=False),
    sa.Column('jenjang', sa.String(length=20), nullable=True),
    sa.Column('wali_kelas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wali_kelas_id'], ['pengajar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('santri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nis', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=10), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('jenjang', sa.String(length=20), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.Column('wali_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['wali_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nis')
    )
    op.create_table('absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keuangan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=True),
    sa.Column('bulan', sa.String(length=20), nullable=True),
    sa.Column('tahun', sa.Integer(), nullable=True),
    sa.Column('jumlah', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tanggal_bayar', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nilai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=True),
    sa.Column('mapel_id', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('nilai_harian', sa.Float(), nullable=True),
    sa.Column('nilai_uts', sa.Float(), nullable=True),
    sa.Column('nilai_uas', sa.Float(), nullable=True),
    sa.Column('nilai_praktik', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mapel_id'], ['mata_pelajaran.id'], ),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tahfidz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=True),
    sa.Column('nama_surat', sa.String(length=50), nullable=True),
    sa.Column('ayat', sa.String(length=50), nullable=True),
    sa.Column('kelancaran', sa.String(length=20), nullable=True),
    sa.Column('tajwid', sa.String(length=20), nullable=True),
    sa.Column('tanggal_setor', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tahfidz')
    op.drop_table('nilai')
    op.drop_table('keuangan')
    op.drop_table('absensi')
    op.drop_table('santri')
    op.drop_table('kelas')
    op.drop_table('pengajar')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('mata_pelajaran')
    # ### end Alembic commands ###
