"""update_raport_model

Revision ID: 9d845167c853
Revises: 440fec423034
Create Date: 2026-02-22 23:42:09.627488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d845167c853'
down_revision = '440fec423034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sakit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('izin', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alpha', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_students', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raport', schema=None) as batch_op:
        batch_op.drop_column('total_students')
        batch_op.drop_column('rank')
        batch_op.drop_column('alpha')
        batch_op.drop_column('izin')
        batch_op.drop_column('sakit')

    # ### end Alembic commands ###
