"""Add Raport model

Revision ID: a3be4b8499ed
Revises: 7cbc6caa438a
Create Date: 2026-02-12 12:35:22.722740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3be4b8499ed'
down_revision = '7cbc6caa438a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('catatan_wali_kelas', sa.Text(), nullable=True),
    sa.Column('status_kenaikan', sa.String(length=50), nullable=True),
    sa.Column('tanggal_bagi', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mata_pelajaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kkm', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mata_pelajaran', schema=None) as batch_op:
        batch_op.drop_column('kkm')

    op.drop_table('raport')
    # ### end Alembic commands ###
