"""empty message

Revision ID: ae03f4b42a34
Revises: fd7e80f4d8fa
Create Date: 2026-02-22 23:10:33.952183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae03f4b42a34'
down_revision = 'fd7e80f4d8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('konfigurasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lembaga', sa.String(length=100), nullable=True),
    sa.Column('alamat_lembaga', sa.Text(), nullable=True),
    sa.Column('logo_kemenag', sa.String(length=255), nullable=True),
    sa.Column('logo_lembaga', sa.String(length=255), nullable=True),
    sa.Column('kepala_sekolah', sa.String(length=100), nullable=True),
    sa.Column('nip_kepala', sa.String(length=50), nullable=True),
    sa.Column('tanggal_raport_default', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('konfigurasi')
    # ### end Alembic commands ###
