"""Add_indexes

Revision ID: c3b1b316d141
Revises: a3be4b8499ed
Create Date: 2026-02-18 21:21:01.148559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b1b316d141'
down_revision = 'a3be4b8499ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('absensi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_absensi_santri_id'), ['santri_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_absensi_tanggal'), ['tanggal'], unique=False)

    with op.batch_alter_table('nilai', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nilai_mapel_id'), ['mapel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nilai_santri_id'), ['santri_id'], unique=False)

    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_santri_kelas_id'), ['kelas_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_santri_wali_user_id'), ['wali_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_santri_wali_user_id'))
        batch_op.drop_index(batch_op.f('ix_santri_kelas_id'))

    with op.batch_alter_table('nilai', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nilai_santri_id'))
        batch_op.drop_index(batch_op.f('ix_nilai_mapel_id'))

    with op.batch_alter_table('absensi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absensi_tanggal'))
        batch_op.drop_index(batch_op.f('ix_absensi_santri_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
