"""empty message

Revision ID: cd87817e734a
Revises: ae03f4b42a34
Create Date: 2026-02-22 23:27:07.114901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd87817e734a'
down_revision = 'ae03f4b42a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nilai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nilai_kehadiran', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nilai', schema=None) as batch_op:
        batch_op.drop_column('nilai_kehadiran')

    # ### end Alembic commands ###
