"""empty message

Revision ID: e3b35158c5e8
Revises: e0fa34c640b8
Create Date: 2026-02-21 23:20:58.863181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b35158c5e8'
down_revision = 'e0fa34c640b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos_keuangan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('tipe', sa.String(length=20), nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=True),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabungan_santri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.String(length=10), nullable=False),
    sa.Column('jumlah', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('saldo_akhir', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaksi_keuangan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=True),
    sa.Column('jumlah', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('jenis', sa.String(length=10), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('metode_pembayaran', sa.String(length=50), nullable=True),
    sa.Column('bukti_pembayaran', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pos_id'], ['pos_keuangan.id'], ),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi_keuangan')
    op.drop_table('tabungan_santri')
    op.drop_table('pos_keuangan')
    # ### end Alembic commands ###
