"""add_kota_ttd

Revision ID: fd4ba6a7af15
Revises: 69e25d86bd1f
Create Date: 2026-02-23 05:31:23.590610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4ba6a7af15'
down_revision = '69e25d86bd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('konfigurasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kota_ttd', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('konfigurasi', schema=None) as batch_op:
        batch_op.drop_column('kota_ttd')

    # ### end Alembic commands ###
