"""empty message

Revision ID: fd7e80f4d8fa
Revises: 764818cd2acd
Create Date: 2026-02-21 23:53:49.812075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7e80f4d8fa'
down_revision = '764818cd2acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabungan_santri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tabungan_santri_santri_id'), ['santri_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tabungan_santri_tanggal'), ['tanggal'], unique=False)

    with op.batch_alter_table('transaksi_keuangan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaksi_keuangan_pos_id'), ['pos_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaksi_keuangan_santri_id'), ['santri_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaksi_keuangan_tanggal'), ['tanggal'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi_keuangan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaksi_keuangan_tanggal'))
        batch_op.drop_index(batch_op.f('ix_transaksi_keuangan_santri_id'))
        batch_op.drop_index(batch_op.f('ix_transaksi_keuangan_pos_id'))

    with op.batch_alter_table('tabungan_santri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tabungan_santri_tanggal'))
        batch_op.drop_index(batch_op.f('ix_tabungan_santri_santri_id'))

    # ### end Alembic commands ###
